#!/bin/sh
. .husky/_/husky.sh

echo 'Running pre-commit Python checks...'

".venv\Scripts\python.exe" -m black --check .
".venv\Scripts\python.exe" -m isort --check-only .
".venv\Scripts\python.exe" -m flake8 .

echo 'Pre-commit checks finished.'
